(ns lein-git-version.plugin
  (:require [clojure.java.io :as io]
            [leiningen.core.main]
            [leiningen.git-version :refer [get-git-version]]
            [robert.hooke :refer (add-hook)]))

(def ^:private default-keys {:assoc-keys [[:version]]})

(defn- version-file [project]
  (let [srcdir (first (filter seq (map #(re-find #".*src$" %) (:source-paths project))))]))

(defn- write-to-version-file [func task-name project args]
  (func task-name project args))

(defn middleware
  [project]
  (let [config (merge default-keys (:git-version project))
        version (get-git-version config)]
    (reduce #(assoc-in %1 %2 version) project (:assoc-keys config))))

;  (let [code (str
;              ";; Do not edit.  Generated by lein-git-version plugin.\n"
;              "(ns " (:name project) ".version)\n"
;              "(def version \"" (get-git-version) "\")\n")
;        filename (str (first (:source-paths project)) "/"
;                      (:name project) "/version.clj")]
;    (-> project
;        (update-in [:injections] concat `[(spit ~filename ~code)])
;        (assoc :version (get-git-version)))))

(defn hooks []
  (add-hook #'leiningen.core.main/apply-task #'write-to-version-file))
